import { Link } from 'react-router-dom';
import { useAuth } from '../../auth/AuthContext';
import { getDaily, getProfile, localDate, fmt, MEALS, hasMeals } from '../../api/user';
import { button, card, secondary, Notice, useLoad, Nutrition } from '../../components/user/ui';
export default function UserDashboardPage(){
 const {user}=useAuth();const date=localDate();const state=useLoad(async()=>({day:await getDaily(date),profile:await getProfile()}),[date]);
 if(state.loading)return <p>Đang tải tổng quan…</p>;
 if(state.error||!state.data)return <div className={card}><Notice error={state.error}/><button className={secondary} onClick={state.reload}>Thử lại</button></div>;
 const {day,profile}=state.data;const target=profile?.targetCalories;const percent=target!=null&&target>0?Math.min(100,Math.max(0,day.totalDailyCalories/target*100)):0;
 return <div className="space-y-5">
  <section className="rounded-2xl bg-navy p-6 text-white shadow-sm"><p className="text-white/80">Chào {user?.fullName} · {date}</p><div className="mt-4 flex flex-wrap items-center gap-8"><div className="relative h-32 w-32"><svg viewBox="0 0 36 36" className="h-full w-full -rotate-90"><circle cx="18" cy="18" r="15.9" fill="none" stroke="#1b3a5c" strokeWidth="3"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="#7fdbff" strokeWidth="3" strokeDasharray={`${percent} 100`}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl">{fmt(day.totalDailyCalories)}</strong><small>kcal đã ghi nhận</small></div></div><div><h2 className="text-3xl font-bold">{target==null?'Theo dõi bữa ăn hôm nay':`${day.totalDailyCalories>target?'Vượt':'Còn'} ${fmt(Math.abs(target-day.totalDailyCalories))} kcal`}</h2><p className="mt-2 text-white/75">{target==null?'Bạn chưa đặt mục tiêu năng lượng.':`Mục tiêu hiện tại: ${fmt(target)} kcal`}</p>{!hasMeals(day)&&<p className="mt-2 text-white/75">Chưa có món ăn được ghi nhận hôm nay.</p>}</div></div><div className="mt-5 flex flex-wrap gap-3"><Link to="/app/recognize" className="rounded-xl bg-accent px-4 py-3 font-semibold text-navy">Nhận diện món ăn</Link><Link to="/app/recognize?mode=search" className="rounded-xl bg-white px-4 py-3 text-navy">Tìm món / Thêm thủ công</Link><Link to={`/app/diary?date=${date}`} className="rounded-xl border border-white/40 px-4 py-3">Xem nhật ký</Link></div></section>
  {!profile&&<div className={card}><p>Thiết lập hồ sơ và mục tiêu để theo dõi tiến độ.</p><Link className={`${button} mt-3`} to="/app/onboarding">Khởi tạo hồ sơ</Link></div>}
  <section className={card}><h3 className="mb-4 font-bold">Dinh dưỡng đã ghi nhận hôm nay</h3><Nutrition data={{calories:day.totalDailyCalories,protein:day.totalDailyProtein,carbs:day.totalDailyCarbs,fat:day.totalDailyFat,fiber:day.totalDailyFiber}}/>{!day.fiberComplete&&<p className="u-muted mt-3 text-sm">Một số món chưa có số liệu chất xơ.</p>}</section>
  <section className={card}><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-bold">Bữa ăn trong ngày</h3><button className={secondary} onClick={state.reload}>Làm mới</button></div><div className="space-y-4">{MEALS.map(([key,name])=>{const meal=day.meals.find(m=>m.mealType===key);return <div key={key} className="u-soft rounded-xl p-4"><div className="mb-3 flex justify-between gap-3"><h4 className="font-semibold">{name}</h4><span>{meal?`${fmt(meal.mealCalories)} kcal`:'Chưa ghi nhận'}</span></div>{meal?.items.map(item=><div key={item.id} className="flex justify-between gap-3 py-2 text-sm"><span>{item.foodName} · {fmt(item.consumedWeightG)} g</span><strong>{fmt(item.actualCalories)} kcal</strong></div>)}<Link to={`/app/recognize?mode=search&date=${date}&meal=${key}`} className="mt-2 inline-block text-secondary underline">+ Thêm món vào {name.toLowerCase()}</Link></div>;})}</div></section>
 </div>;
}
